// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seismic.Data.Context;

#nullable disable

namespace Seismic.Data.Migrations
{
    [DbContext(typeof(SeismicDbContext))]
    [Migration("20260301020059_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Seismic.Data.Entities.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("MonitorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RawCsvPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("ScaledDistance")
                        .HasColumnType("float");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("WeightPerDelay")
                        .HasColumnType("float");

                    b.HasKey("EventId");

                    b.HasIndex("EventTimestamp");

                    b.HasIndex("SiteId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Seismic.Data.Entities.MonitorHealth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("EnergySymmetry")
                        .HasColumnType("float");

                    b.Property<double>("HealthScore")
                        .HasColumnType("float");

                    b.Property<string>("MonitorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("R2Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId", "Date");

                    b.ToTable("MonitorHealths", (string)null);
                });

            modelBuilder.Entity("Seismic.Data.Entities.WaveformPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("A")
                        .HasColumnType("float");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("R")
                        .HasColumnType("float");

                    b.Property<double>("T")
                        .HasColumnType("float");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.Property<double>("V")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("WaveformPoints", (string)null);
                });

            modelBuilder.Entity("Seismic.Data.Entities.WaveformPoint", b =>
                {
                    b.HasOne("Seismic.Data.Entities.Event", "Event")
                        .WithMany("WaveformPoints")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Seismic.Data.Entities.Event", b =>
                {
                    b.Navigation("WaveformPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
